steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=secrets.json.enc
  - --plaintext-file=secrets.json
  - --location=global
  - --keyring=pspkeyring
  - --key=uisecrets
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/psp', '.']
  env:
  - 'BUILD=$BUILD_ID'
  - 'COMMIT=$SHORT_SHA'
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/psp']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'psp','--namespace', 'prod', '--image', 'gcr.io/$PROJECT_ID/psp','--cluster', 'psp-cluster-1', '--cluster-location', 'us-central1-a']
substitutions:
    _SUB_VALUE: unused
options:
    substitution_option: 'ALLOW_LOOSE'
images:
- gcr.io/$PROJECT_ID/psp